/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as GoogleAdsToolRouteImport } from './routes/google-ads-tool'
import { Route as DigitalSignageForSchoolsRouteImport } from './routes/digital-signage-for-schools'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as DevMdxTestRouteImport } from './routes/dev.mdx-test'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleAdsToolRoute = GoogleAdsToolRouteImport.update({
  id: '/google-ads-tool',
  path: '/google-ads-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalSignageForSchoolsRoute =
  DigitalSignageForSchoolsRouteImport.update({
    id: '/digital-signage-for-schools',
    path: '/digital-signage-for-schools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMdxTestRoute = DevMdxTestRouteImport.update({
  id: '/dev/mdx-test',
  path: '/dev/mdx-test',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/digital-signage-for-schools': typeof DigitalSignageForSchoolsRoute
  '/google-ads-tool': typeof GoogleAdsToolRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/dev/mdx-test': typeof DevMdxTestRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/digital-signage-for-schools': typeof DigitalSignageForSchoolsRoute
  '/google-ads-tool': typeof GoogleAdsToolRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/dev/mdx-test': typeof DevMdxTestRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/digital-signage-for-schools': typeof DigitalSignageForSchoolsRoute
  '/google-ads-tool': typeof GoogleAdsToolRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/dev/mdx-test': typeof DevMdxTestRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-us'
    | '/digital-signage-for-schools'
    | '/google-ads-tool'
    | '/privacy-policy'
    | '/terms'
    | '/dev/mdx-test'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/digital-signage-for-schools'
    | '/google-ads-tool'
    | '/privacy-policy'
    | '/terms'
    | '/dev/mdx-test'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact-us'
    | '/digital-signage-for-schools'
    | '/google-ads-tool'
    | '/privacy-policy'
    | '/terms'
    | '/dev/mdx-test'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactUsRoute: typeof ContactUsRoute
  DigitalSignageForSchoolsRoute: typeof DigitalSignageForSchoolsRoute
  GoogleAdsToolRoute: typeof GoogleAdsToolRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  DevMdxTestRoute: typeof DevMdxTestRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-ads-tool': {
      id: '/google-ads-tool'
      path: '/google-ads-tool'
      fullPath: '/google-ads-tool'
      preLoaderRoute: typeof GoogleAdsToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-signage-for-schools': {
      id: '/digital-signage-for-schools'
      path: '/digital-signage-for-schools'
      fullPath: '/digital-signage-for-schools'
      preLoaderRoute: typeof DigitalSignageForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/mdx-test': {
      id: '/dev/mdx-test'
      path: '/dev/mdx-test'
      fullPath: '/dev/mdx-test'
      preLoaderRoute: typeof DevMdxTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactUsRoute: ContactUsRoute,
  DigitalSignageForSchoolsRoute: DigitalSignageForSchoolsRoute,
  GoogleAdsToolRoute: GoogleAdsToolRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  DevMdxTestRoute: DevMdxTestRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
